phrase:
  access_token: ea5c8dc75d258ae1abc3418d70f6edb3e47392aa9ebb1f00cb7566ad6d1e9916
  project_id: a3f13a30a1db71c3305a751b525657d7
  push:
    sources:
    - file: ./src/i18n/locales/<locale_name>/translation.json
      params:
        file_format: i18next_4
  pull:
    targets:
    - file: ./src/i18n/locales/<locale_name>/translation.json
      params:
        file_format: i18next_4

























