phrase:
  access_token: ea5c8dc75d258ae1abc3418d70f6edb3e47392aa9ebb1f00cb7566ad6d1e9916
  project_id: a4e7d5f425cf5a7f639a3601f8450b12
  push:
    sources:
    - file: ./testuser.json
      params:
        file_format: i18next_4
        locale_id: df7ff9742697b2bb4e5c2e4ce07ef350
        update_translations: false
  pull:
    targets:
    - file: ./testuser_it.json
      params:
        file_format: i18next_4
        locale_id: 30cfca4847bb590622aa36da301d8a5d












