phrase:
  access_token: ea5c8dc75d258ae1abc3418d70f6edb3e47392aa9ebb1f00cb7566ad6d1e9916
  project_id: a3f13a30a1db71c3305a751b525657d7
  push:
    sources:
      - file: ./source_file/i18n/locales/en/new2.json
        params:
          file_format: i18next_4
          tags: new2
          locale_id: cea21ab6a01c6cd1a184465c58b49d71
          autotranslate: true
          update_translations: true

      - file: ./source_file/i18n/locales/en/new3.json
        params:
          file_format: i18next_4
          tags: new3
          locale_id: cea21ab6a01c6cd1a184465c58b49d71
          autotranslate: true
          update_translations: true

      - file: ./source_file/i18n/locales/en/new4.json
        params:
          file_format: i18next_4
          tags: new4
          locale_id: cea21ab6a01c6cd1a184465c58b49d71
          autotranslate: true
          update_translations: true

  pull:
    targets:
      - file: ./source_file/i18n/locales/it/new2_target.json
        params:
          file_format: i18next_4
          tags: new2_target
          locale_id: 6767b2427e4c03881bef5a304654b0df

      - file: ./source_file/i18n/locales/it/new3_target.json
        params:
          file_format: i18next_4
          tags: new3_target
          locale_id: 6767b2427e4c03881bef5a304654b0df

      - file: ./source_file/i18n/locales/it/new4_target.json
        params:
          file_format: i18next_4
          tags: new4_target
          locale_id: 6767b2427e4c03881bef5a304654b0df






































