phrase:
  project_id: 74479b8537d5a513673d36eb0d790696
  file_format: yml

  push:
    sources:
    - file: en.yml
      params:
        file_format: yml
        locale_id: df7ff9742697b2bb4e5c2e4ce07ef350
        
  pull:
    targets:
    - file: en.yml
      params:
        file_format: yml
        locale_id: 30cfca4847bb590622aa36da301d8a5d

        
