phrase:
  access_token: ea5c8dc75d258ae1abc3418d70f6edb3e47392aa9ebb1f00cb7566ad6d1e9916
  project_id: a4e7d5f425cf5a7f639a3601f8450b12
  push:
    sources:
    - file: ./src/i18n/locales/<locale_name>/testuser.json
      params:
        file_format: i18next_4
        locale_id: a923bb5499fe7ece5a824de7d4adb123
        update_translations: false
  pull:
    targets:
    - file: ./src/i18n/locales/<locale_name>/ttestuser_it.json
      params:
        file_format: i18next_4
        locale_id: e7810268d4d542c8dfd9f9950f502f6c














