phrase:
  access_token: ea5c8dc75d258ae1abc3418d70f6edb3e47392aa9ebb1f00cb7566ad6d1e9916
  project_id: a4e7d5f425cf5a7f639a3601f8450b12
  push:
    sources:
    - file: C:/Users/Lorenza/Downloads/Phrase_TSA_Test_FIles_(1)/en.yml
      params:
        file_format: yml
  pull:
    targets:
    - file: C:/Users/Lorenza/Downloads/Phrase_TSA_Test_FIles_(1)/en.yml
      params:
        file_format: yml
